#!/usr/bin/env bash

brew install \
  bash \
  curl \
  difftastic \
  eza \
  fd \
  fzf \
  gh \
  git \
  git-lfs \
  gnu-sed \
  go \
  jq \
  lazygit \
  luajit \
  mergiraf \
  neovim \
  newt \
  node \
  ripgrep \
  rustup \
  sqlite \
  starship \
  stow \
  tmux \
  tokei \
  tree \
  tree-sitter \
  tree-sitter-cli \
  wget \
  z.lua \
  zsh \
  zsh-syntax-highlighting
