#!/usr/bin/env bash

stow -vt ~ git tmux nvim kitty zsh fish starship

if [ ! -L "/usr/local/bin/tmux-sessionizer" ]; then
  sudo ln -sf ~/code/dotfiles/scripts/tmux-sessionizer /usr/local/bin/tmux-sessionizer
fi
