#!/usr/bin/env bash

stow -vt ~ git tmux nvim kitty zsh fish starship

for script in scripts/*; do
  [ -f "$script" ] || continue
  sudo ln -sf "$PWD/$script" "/usr/local/bin/$(basename "$script")"
done
